[phases.setup]
nixPkgs = ["bash", "git", "curl", "unzip", "which", "nodejs_20", "flutter"]

[phases.build]
cmds = [
  "flutter --version",
  "flutter pub get",
  "flutter build web --release"
]

[start]
cmd = "node server.js"
