# Tell Nixpacks to install the tools we need
[phases.setup]
aptPkgs = [
  "git",
  "curl",
  "unzip",
  "xz-utils",
  "ca-certificates",
  "nodejs"
]

# Download & install Flutter (stable) into /opt/flutter and put it on PATH
cmds = [
  "set -eux",
  "FLUTTER_URL=https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz",
  "mkdir -p /opt",
  "curl -fsSL $FLUTTER_URL -o /tmp/flutter.tar.xz",
  "tar -xJf /tmp/flutter.tar.xz -C /opt",
  "ln -sf /opt/flutter/bin/flutter /usr/local/bin/flutter",
  "flutter --version",
  "flutter config --enable-web",
  "flutter precache --web"
]

[phases.install]
# Install Node deps for the tiny web host
cmds = ["npm ci --omit=dev || npm i --omit=dev"]

[phases.build]
# Build Flutter Web bundle
cmds = [
  "flutter pub get",
  "flutter build web --release"
]

[start]
# Serve the compiled bundle with Express
cmd = "node server.js"
