# --- Nixpacks config for Flutter web + Node host ---

[phases.setup]
nixPkgs = ["bash", "curl", "unzip", "git", "nodejs_20"]

[phases.install]
cmds = [
  'set -eux',
  'FLUTTER_VERSION=3.35.1',
  'FLUTTER_URL=https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz',
  'mkdir -p /opt',
  'curl -fsSL "$FLUTTER_URL" -o /tmp/flutter.tar.xz',
  'tar -xf /tmp/flutter.tar.xz -C /opt',
  'export PATH=/opt/flutter/flutter/bin:$PATH',
  'flutter config --enable-web',
  'flutter doctor -v',
  'flutter pub get'
]

[phases.build]
cmds = [
  'export PATH=/opt/flutter/flutter/bin:$PATH',
  # inject the backend URL into the Flutter build
  'flutter build web --release --dart-define=API_URL=${POTBOT_API_URL}',
  'npm ci || npm i'
]

[start]
cmd = "node server.js"

includes = ["build/web", "server.js", "package.json"]
