# --- Nixpacks config for Flutter web + Node host ---

[phases.setup]
# tools needed during build
nixPkgs = ["bash", "curl", "unzip", "git", "nodejs_20"]

[phases.install]
# Install Flutter 3.35.1 (Dart 3.9) and prep environment
cmds = [
  "set -eux",
  "FLUTTER_VERSION=3.35.1",
  "FLUTTER_URL=https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz",
  "mkdir -p /opt",
  "curl -fsSL \"$FLUTTER_URL\" -o /tmp/flutter.tar.xz",
  "tar -xf /tmp/flutter.tar.xz -C /opt",
  "export PATH=/opt/flutter/flutter/bin:$PATH",
  "flutter config --enable-web",
  "flutter doctor -v",
  "flutter pub get"
]

[phases.build]
# Build Flutter web and install Node deps for the server
cmds = [
  "export PATH=/opt/flutter/flutter/bin:$PATH",
  "rm -rf build",  # ensure no stale web assets
  # Inject POTBOT_API_URL -> API_URL used by Dart (String.fromEnvironment('API_URL'))
  "flutter build web --release --pwa-strategy=none --dart-define=API_URL=${POTBOT_API_URL}",
  "npm ci || npm i"
]

[start]
# Serve compiled web via our Node server
cmd = "node server.js"

# Keep these files in the final image
includes = ["build/web", "server.js", "package.json"]
