# Dart analyzer config
# Docs: https://dart.dev/guides/language/analysis-options

# Use Flutter’s recommended lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # project-specific tweaks
    avoid_print: false
    prefer_single_quotes: true
    # silence the noisy warnings you saw in VS Code
    unnecessary_underscores: false