name: potbot_frontend_flutter
description: PotBot – AI-powered cannabis quality scanner and grow assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # Dart SDK range compatible with recent Flutter 3.x

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Camera / images
  image_picker: ^1.0.5

  # Files / paths
  path_provider: ^2.1.2

  # .env + HTTP
  flutter_dotenv: ^5.1.0
  http: ^1.2.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # Add assets here if needed in the future
  assets:
    - assets/images/
    - .env