name: potbot_frontend_flutter
description: PotBot – AI-powered cannabis quality scanner and grow assistant
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  image_picker: ^1.0.7
  permission_handler: ^12.0.1
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.2
  flutter_dotenv: ^6.0.0 # for local dev only (web build uses --dart-define)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
