name: potbot_frontend_flutter
description: PotBot – AI-powered cannabis quality scanner and grow assistant
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  permission_handler: ^12.0.2
  path_provider: ^2.1.4
  path: ^1.9.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  # Web-specific configuration
  web:
    # Ensure proper MIME types for assets
    meta:
      charset: utf-8
