name: potbot_flutter
description: PotBot frontend Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Camera (live preview on Android/iOS; on web you’ll pick files)
  camera: ^0.11.0+2

  # Image/file picking (gallery/camera stills)
  image_picker: ^1.0.7

  # Permissions (Android/iOS)
  permission_handler: ^11.3.1

  # Files / paths
  path_provider: ^2.1.3
  path: ^1.9.0

  # HTTP client
  http: ^1.2.2

  # Optional: env via dart-define (keep for local/dev)
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/