name: potbot_frontend_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Material
  cupertino_icons: ^1.0.8

  # Camera + Image Picker
  camera: ^0.10.5+5
  image_picker: ^1.0.5

  # File system / paths
  path_provider: ^2.1.2

  # Permissions
  permission_handler: ^11.3.0

  # Geolocation (for Grower Mode, etc.)
  geolocator: ^10.1.0

  # Firebase (optional, comment out if not using Firebase yet)
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # Device info and local storage
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4

  # Notifications
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
