name: potbot
description: PotBot — AI‑powered cannabis quality scanner and grow assistant.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Material
  cupertino_icons: ^1.0.8

  # Camera + Image Picker
  camera: ^0.10.5+5
  image_picker: ^1.0.5

  # File system / paths
  path_provider: ^2.1.2
  path: ^1.9.0

  # Permissions
  permission_handler: ^11.3.0

  # Geolocation (optional for grower mode)
  geolocator: ^10.1.0

  # .env loader + HTTP client
  flutter_dotenv: ^5.1.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
