name: Build Android App Bundle (Flutter)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'   # or pin a version: flutter-version: '3.22.2'

      - name: Flutter pub get
        run: flutter pub get

      # Optional but helpful if you ever need to recreate platform files
      # - name: Ensure android files exist
      #   run: flutter create .

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
