name: Build Android App Bundle with Capacitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      # Node LTS version
      NODE_VERSION: '20'
      # Correct way to reference runner temp directory
      ANDROID_SDK_ROOT: $RUNNER_TEMP/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Continue with the rest of your build steps...
