name: Build & Deploy Flutter Web to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'   # match your local flutter --version
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: |
          flutter build web --release \
            --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }} \
            --dart-define=REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }} \
            --dart-define=BUILD_TIME=${{ github.run_id }}

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy build/web to Railway (frontend)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service "potbot-frontend" --path "build/web" --detach
