name: Build Android App Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android AAB with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack for Yarn 4
        run: corepack enable

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build frontend
        run: yarn build
        working-directory: ./frontend

      - name: Install Capacitor CLI via Yarn DLX
        run: yarn dlx @capacitor/cli --version
        working-directory: ./frontend

      - name: Sync Capacitor
        run: yarn dlx @capacitor/cli sync android
        working-directory: ./frontend

      - name: Copy web assets
        run: yarn dlx @capacitor/cli copy android
        working-directory: ./frontend

      - name: Set Gradlew permissions
        run: chmod +x android/gradlew
        working-directory: ./frontend

      - name: Build AAB
        run: ./gradlew bundleRelease
        working-directory: ./frontend/android

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: frontend/android/app/build/outputs/bundle/release/app-release.aab
