name: Build Android App Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android App Bundle with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack for Yarn 4
        run: corepack enable

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: yarn install

      - name: Install Capacitor CLI locally
        run: yarn add @capacitor/cli

      - name: Build frontend
        run: yarn build

      - name: Sync Capacitor
        run: yarn exec cap sync android

      - name: Copy web assets to Android
        run: yarn exec cap copy android

      - name: Grant Gradlew permissions
        run: chmod +x android/gradlew

      - name: Build AAB
        run: cd android && ./gradlew bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
