name: Build & Deploy Flutter Web to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'   # ✅ ships with Dart 3.7.x

      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: flutter build web --release

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy build/web to Railway service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service potbot-frontend --path build/web --detach
