name: Build Flutter Web → webhost/ (main branch)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Enable web & get deps
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Build web (release)
        run: flutter build web --release

      - name: Stage runtime into webhost/
        run: |
          mkdir -p webhost
          rm -rf webhost/*
          mkdir -p webhost/public
          cp -r build/web/* webhost/public/
          cp server.js webhost/
          cp package.json webhost/
          echo "web: node server.js" > webhost/Procfile

      - name: Commit webhost/ to main
        run: |
          git add -A webhost
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "ci: update webhost from Flutter build" || echo "No changes to commit"
          git push
