name: Build Flutter Web → deploy-web branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Enable web & get deps
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Build web (release)
        run: flutter build web --release

      - name: Stage Node runtime
        run: |
          mkdir -p deploy_web_out
          cp -r build/web deploy_web_out/public
          cp server.js deploy_web_out/
          cp package.json deploy_web_out/
          echo "web: node server.js" > deploy_web_out/Procfile

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy_web_out
          path: deploy_web_out

      # === new job to switch branches and commit ===
  publish-web:
    runs-on: ubuntu-latest
    needs: build-web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy_web_out
          path: deploy_web_out

      - name: Switch to deploy-web branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/deploy-web; then
            git checkout deploy-web
          else
            git checkout --orphan deploy-web
            git rm -rf . || true
          fi

      - name: Replace contents and commit
        run: |
          rm -rf ./*
          cp -r deploy_web_out/* .
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "ci: deploy Flutter web $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"

      - name: Push deploy-web
        run: git push -f origin deploy-web
